import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "@/components/AuthProvider/AuthProvider";
import ReduxProvider from "@/store/ReduxProvider";
import NotificationList from "@/store/NotificationList";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <AuthProvider>
            <NotificationList />
            <div>
              {children}
            </div>
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
